### ISSUE TITLE
npm install 会安装不了node-sass，cnpm install也出错，不知道如何解决了，折腾一天了

### ISSUE THREAD

**Issue by forconz** [zxj963577494/Ionic2-CNodeClub#3]
cnpm install
/ [63/65] Installing camelcase@^3.0.0platform unsupported @ionic/app-scripts@1.3.7 › chokidar@1.6.1 › fsevents@^1.0.0 Package require os(darwin) not compatible with your platform(win32)
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(win32)
√ Installed 65 packages
√ Linked 610 latest versions
Cached binary found at C:\Users\lenovo\.npminstall_tarball\node-sass\4.5.3\win32-x64-57_binding.node
Binary found at D:\Club\source\ionic\node_modules\_node-sass@4.5.3@node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.5.0/win32-x64-57_binding.node
Cannot download "https://npm.taobao.org/mirrors/node-sass/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
Building: C:\Program Files\nodejs\node.exe D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Club\\source\\ionic\\node_modules\\_node-gyp@3.6.2@node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/mirrors/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:13:12)\n    at F (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:68:19)\n    at E (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:80:29)\n    at D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:89:16\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:13:12)\n    at F (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:68:19)\n    at E (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:80:29)\n    at D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:89:16\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Club\source\ionic\node_modules\_graceful-fs@4.1.11@graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Club\\source\\ionic\\node_modules\\_node-gyp@3.6.2@node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Club\source\ionic\node_modules\_node-sass@4.5.0@node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npminstall version: 3.1.4
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\lenovo\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\lenovo\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://registry.npm.taobao.org

**然后rebuild这个node-sass，也发现一堆错**

cnpm rebuild node-sass

> node-sass@4.5.3 install D:\Club\source\ionic\node_modules\_node-sass@4.5.3@node-sass
> node scripts/install.js

node-sass build Binary found at D:\Club\source\ionic\node_modules\_node-sass@4.5.3@node-sass\vendor\win32-x64-57\binding.node

> node-sass@4.5.3 postinstall D:\Club\source\ionic\node_modules\_node-sass@4.5.3@node-sass
> node scripts/build.js

Binary found at D:\Club\source\ionic\node_modules\_node-sass@4.5.3@node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> node-sass@4.5.0 install D:\Club\source\ionic\node_modules\_node-sass@4.5.0@node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.5.0 postinstall D:\Club\source\ionic\node_modules\_node-sass@4.5.0@node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Club\\source\\ionic\\node_modules\\_node-gyp@3.6.2@node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.4.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/mirrors/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:13:12)\n    at F (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:68:19)\n    at E (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:80:29)\n    at D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:89:16\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:13:12)
gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:68:19)
gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:80:29)
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_which@1.3.0@which\which.js:89:16
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\index.js:42:5
gyp verb `which` failed     at D:\Club\source\ionic\node_modules\_isexe@2.0.0@isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:13:12)\n    at F (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:68:19)\n    at E (D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:80:29)\n    at D:\\Club\\source\\ionic\\node_modules\\_which@1.3.0@which\\which.js:89:16\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\index.js:42:5\n    at D:\\Club\\source\\ionic\\node_modules\\_isexe@2.0.0@isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Club\source\ionic\node_modules\_node-gyp@3.6.2@node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\Club\source\ionic\node_modules\_graceful-fs@4.1.11@graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Club\\source\\ionic\\node_modules\\_node-gyp@3.6.2@node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Club\source\ionic\node_modules\_node-sass@4.5.0@node-sass
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-09-10T13_28_19_086Z-debug.log

**Comment by forconz** [comment]
我正在下载 python2.7.13，不知道安装这个后，会怎样，总而言之npm install 通不过，ionic serve跑不起来有原因的，install有问题。

我删了node_modules，重新开始安装。
ionic serve

? Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? Yes
[INFO] Installing dependencies may take several minutes!
> npm install
\ Running command

**Comment by forconz** [comment]
> npm install
× Running command - failed!
[ERROR] An error occurred while running npm install (exit code 1):


        npm WARN deprecated @ionic/cli-plugin-cordova@1.4.0: Ionic CLI 3.8 no longer loads this plugin. See
        https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#3.8.0
        npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-minify
        npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to
        babel-preset-minify
        npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

        > node-sass@4.5.0 install D:\Club\source\ionic\node_modules\@ionic\app-scripts\node_modules\node-sass
        > node scripts/install.js

        Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node
        Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.0/win32-x64-57_binding.node":

        HTTP error 404 Not Found

        Hint: If github.com is not accessible in your location
               try setting a proxy via HTTP_PROXY, e.g.

               export HTTP_PROXY=http://example.com:1234

        or configure npm proxy via

               npm config set proxy http://example.com:8080

        > node-sass@4.5.3 install D:\Club\source\ionic\node_modules\node-sass
        > node scripts/install.js

        Cached binary found at C:\Users\lenovo\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-57_binding.node

        > node-sass@4.5.0 postinstall D:\Club\source\ionic\node_modules\@ionic\app-scripts\node_modules\node-sass
        > node scripts/build.js

        Building: C:\Program Files\nodejs\node.exe D:\Club\source\ionic\node_modules\node-gyp\bin\node-gyp.js rebuild
        --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
        gyp info it worked if it ends with ok
        gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
        gyp verb cli   'D:\\Club\\source\\ionic\\node_modules\\node-gyp\\bin\\node-gyp.js',
        gyp verb cli   'rebuild',
        gyp verb cli   '--verbose',
        gyp verb cli   '--libsass_ext=',
        gyp verb cli   '--libsass_cflags=',
        gyp verb cli   '--libsass_ldflags=',
        gyp verb cli   '--libsass_library=' ]
        gyp info using node-gyp@3.6.2
        gyp info using node@8.4.0 | win32 | x64
        gyp verb command rebuild []
        gyp verb command clean []
        gyp verb clean removing "build" directory
        gyp verb command configure []
        gyp verb check python checking for Python executable "python2" in the PATH
        gyp verb `which` failed Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\which\which.js:89:16
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python2 { Error: not found: python2
        gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\which\which.js:89:16
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:13:12)\n    at F
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:68:19)\n    at E
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:80:29)\n    at
        D:\\Club\\source\\ionic\\node_modules\\which\\which.js:89:16\n    at
        D:\\Club\\source\\ionic\\node_modules\\isexe\\index.js:42:5\n    at
        D:\\Club\\source\\ionic\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb check python checking for Python executable "python" in the PATH
        gyp verb `which` failed Error: not found: python
        gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\which\which.js:89:16
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed  python { Error: not found: python
        gyp verb `which` failed     at getNotFoundError (D:\Club\source\ionic\node_modules\which\which.js:13:12)
        gyp verb `which` failed     at F (D:\Club\source\ionic\node_modules\which\which.js:68:19)
        gyp verb `which` failed     at E (D:\Club\source\ionic\node_modules\which\which.js:80:29)
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\which\which.js:89:16
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\index.js:42:5
        gyp verb `which` failed     at D:\Club\source\ionic\node_modules\isexe\windows.js:36:5
        gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:13:12)\n    at F
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:68:19)\n    at E
        (D:\\Club\\source\\ionic\\node_modules\\which\\which.js:80:29)\n    at
        D:\\Club\\source\\ionic\\node_modules\\which\\which.js:89:16\n    at
        D:\\Club\\source\\ionic\\node_modules\\isexe\\index.js:42:5\n    at
        D:\\Club\\source\\ionic\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
        gyp verb `which` failed   code: 'ENOENT' }
        gyp verb could not find "python". checking python launcher
        gyp verb could not find "python". guessing location
        gyp verb ensuring that file exists: C:\Python27\python.exe
        gyp ERR! configure error
        gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
        gyp ERR! stack     at PythonFinder.failNoPython
        (D:\Club\source\ionic\node_modules\node-gyp\lib\configure.js:483:19)
        gyp ERR! stack     at PythonFinder.<anonymous>
        (D:\Club\source\ionic\node_modules\node-gyp\lib\configure.js:508:16)
        gyp ERR! stack     at D:\Club\source\ionic\node_modules\graceful-fs\polyfills.js:284:29
        gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
        gyp ERR! System Windows_NT 10.0.14393
        gyp ERR! command "C:\\Program Files\\nodejs\\node.exe"
        "D:\\Club\\source\\ionic\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext="
        "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
        gyp ERR! cwd D:\Club\source\ionic\node_modules\@ionic\app-scripts\node_modules\node-sass
        gyp ERR! node -v v8.4.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        Build failed with error code: 1
        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
        npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted
        {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! node-sass@4.5.0 postinstall: `node scripts/build.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the node-sass@4.5.0 postinstall script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-09-10T14_05_11_253Z-debug.log

**Comment by zxj963577494** [comment]
重新安装node.js或使用代理安装
